// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WebApplication.Models;

namespace WebApplication.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180612141923_AddedLog")]
    partial class AddedLog
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication.Models.Timer.TimerActivity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("TimerActivities");
                });

            modelBuilder.Entity("WebApplication.Models.Timer.TimerLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ActivityID");

                    b.Property<DateTime>("Date");

                    b.HasKey("ID");

                    b.HasIndex("ActivityID");

                    b.ToTable("TimerLogs");
                });

            modelBuilder.Entity("WebApplication.Models.Timer.TimerSound", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Data");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("TimerSounds");
                });

            modelBuilder.Entity("WebApplication.Models.Timer.TimerLog", b =>
                {
                    b.HasOne("WebApplication.Models.Timer.TimerActivity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityID");
                });
#pragma warning restore 612, 618
        }
    }
}
